name: Tutorial1
version: ${project.version}
main: net.noodles.tutorial1.main.Main
authors: [Noodles]
description: Plugin Tutorial Video Plugin
website: https://bghddevelopment.com
commands:
  tutorial:
  fly:
  tp:
